// <auto-generated />
namespace HotelProctors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relation123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relation123));
        
        string IMigrationMetadata.Id
        {
            get { return "202001111649474_Relation123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
